module.exports = {
  title: '{{PROJECT_NAME}}',
  tagline: '{{TAGLINE}}',
  url: 'https://docs.sorodoc.dev',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'sorodoc',
  projectName: '{{PROJECT_SLUG}}',
  themeConfig: {
    navbar: {
      title: '{{PROJECT_NAME}}',
      items: [
        { to: '/docs/overview', label: 'Docs', position: 'left' },
        { to: '/docs/sdk/quickstart', label: 'SDK', position: 'left' },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: 'Generated by SoroDoc',
    },
  },
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: undefined,
        },
        theme: { customCss: require.resolve('./src/css/custom.css') },
      },
    ],
  ],
};
