import { type ContractABI, type DocOutput, type SDKOutput } from '../types.js';

export interface PythonSDKOptions {
  abi: ContractABI;
  docOutput?: DocOutput;
  packageName: string;
  version?: string;
  network?: string;
  contractId?: string;
}

function sorobanToPy(type: { kind: string; element?: unknown; key?: unknown; value?: unknown; inner?: unknown; ok?: unknown; name?: string }): string {
  switch (type.kind) {
    case 'val': case 'address': case 'symbol': case 'string': case 'bytes': case 'muxedAddress': return 'str';
    case 'bool': return 'bool';
    case 'void': return 'None';
    case 'error': return 'str';
    case 'i32': case 'i64': case 'i128': case 'i256': case 'u32': case 'u64': case 'u128': case 'u256': return 'int';
    case 'timepoint': case 'duration': return 'int';
    case 'vec': return `list[${sorobanToPy(type.element as any)}]`;
    case 'map': return `dict[${sorobanToPy(type.key as any)}, ${sorobanToPy(type.value as any)}]`;
    case 'option': return `Optional[${sorobanToPy(type.inner as any)}]`;
    case 'result': return sorobanToPy(type.ok as any);
    case 'struct': case 'enum': case 'union': case 'udt': return type.name || 'Any';
    case 'tuple': return 'tuple';
    default: return 'Any';
  }
}

function capitalize(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function snakeCase(name: string): string {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

function generateDataclasses(abi: ContractABI): string {
  return abi.functions.filter(fn => fn.params.length > 0).map(fn => {
    const fields = fn.params.map(p => `    ${snakeCase(p.name)}: ${sorobanToPy(p.type)}  # ${p.docs || ''}`).join('\n');
    const docComment = `"""Parameters for the ${fn.name} function."""`;
    return `@dataclass\nclass ${capitalize(fn.name)}Params:\n${fields ? `    ${docComment}\n${fields}` : '    pass'}`;
  }).join('\n\n');
}

function generateMethods(abi: ContractABI): string {
  return abi.functions.map(fn => {
    const hasParams = fn.params.length > 0;
    const paramStr = hasParams ? `params: ${capitalize(fn.name)}Params, source_keypair: Keypair` : 'source_keypair: Keypair';
    const returnHint = fn.returns.kind === 'void' ? 'None' : sorobanToPy(fn.returns);
    return `    def ${snakeCase(fn.name)}(self, ${paramStr}) -> ${returnHint}:\n        """\n        ${fn.docs || `${fn.name} — contract function.`}\n\n        Args:\n${hasParams ? `            params: Parameters for ${fn.name}.\n` : ''}            source_keypair: Keypair of the transaction source.\n        """\n        return None`;
  }).join('\n\n');
}

export function generatePythonSDK(opts: PythonSDKOptions): SDKOutput {
  const { abi, packageName, version, network, contractId } = opts;

  const dataclasses = generateDataclasses(abi);
  const methods = generateMethods(abi);

  const networkPassphrase = network === 'mainnet'
    ? 'Keypair.from_secret("...").network_passphrase  # Public Global Stellar Network ; September 2015'
    : 'Keypair.from_secret("...").network_passphrase  # Test SDF Network ; September 2015';

  const rpcUrl = network === 'mainnet'
    ? 'https://soroban-rpc.mainnet.stellar.org'
    : 'https://soroban-rpc.testnet.stellar.org';

  const metaLines = [
    `${abi.name} SDK`,
    packageName,
    contractId ? `Contract ID: ${contractId}` : '',
    network ? `Network: ${network}` : '',
    '',
    'Auto-generated by SoroDoc.',
  ].filter(Boolean).join('\n');

  const classDocLines = [
    `Client for the ${abi.name} Soroban smart contract.`,
    '',
    'Auto-generated by SoroDoc from contract ABI.',
    contractId ? `Contract ID: ${contractId}` : '',
    network ? `Network: ${network}` : '',
  ].filter(Boolean).join('\n    ');

  const content = `"""
${metaLines}
"""

from dataclasses import dataclass
from typing import Optional, Any
from stellar_sdk import Keypair
from stellar_sdk.soroban_server import SorobanServer

${dataclasses}


class ${abi.name}Contract:
    """
    ${classDocLines}
    """

    def __init__(
        self,
        contract_id: str,
        rpc_url: str = "${rpcUrl}",
        network_passphrase: str = None,
    ):
        self.contract_id = contract_id
        self.server = SorobanServer(rpc_url)
        self.network_passphrase = network_passphrase or ${networkPassphrase}

${methods}
`;

  const files = new Map<string, string>();
  files.set('contract.py', content);

  const pyPkgName = packageName.replace(/[@\/-]/g, '_');
  files.set('pyproject.toml', `[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "${abi.name.toLowerCase()}-sdk"
version = "${version || '0.1.0'}"
description = "${abi.name} Soroban contract SDK"
dependencies = [
    "stellar-sdk>=11.0.0",
]
`);

  const readme = `# ${abi.name} SDK

${abi.name} — Soroban Smart Contract Python SDK

**Package:** \`${packageName}\`
${contractId ? `**Contract ID:** \`${contractId}\`` : ''}

## Installation

\`\`\`bash
pip install ${abi.name.toLowerCase()}-sdk
\`\`\`

## Usage

\`\`\`python
from ${pyPkgName} import ${abi.name}Contract

contract = ${abi.name}Contract(
    contract_id="${contractId || 'YOUR_CONTRACT_ID'}",
)
\`\`\`

---

*Generated by SoroDoc*
`;

  return { files, packageJson: { name: packageName, version: version || '0.1.0' }, readme };
}
