import { type ContractABI, type DocOutput, type SDKOutput } from '../types.js';

export interface RustClientOptions {
  abi: ContractABI;
  docOutput?: DocOutput;
  packageName: string;
  version?: string;
  network?: string;
  contractId?: string;
}

function sorobanToRust(type: { kind: string; name?: string; element?: unknown; key?: unknown; value?: unknown; inner?: unknown; ok?: unknown }): string {
  switch (type.kind) {
    case 'val': return 'Val';
    case 'address': return 'Address';
    case 'bool': return 'bool';
    case 'void': return '()';
    case 'error': return 'Error';
    case 'i32': return 'i32';
    case 'i64': return 'i64';
    case 'i128': return 'i128';
    case 'i256': return 'i256';
    case 'u32': return 'u32';
    case 'u64': return 'u64';
    case 'u128': return 'u128';
    case 'u256': return 'u256';
    case 'symbol': return 'Symbol';
    case 'string': return 'String';
    case 'timepoint': return 'Timepoint';
    case 'duration': return 'Duration';
    case 'muxedAddress': return 'Address';
    case 'bytes': return 'Vec<u8>';
    case 'vec': return `Vec<${sorobanToRust(type.element as any)}>`;
    case 'map': return `Map<${sorobanToRust(type.key as any)}, ${sorobanToRust(type.value as any)}>`;
    case 'option': return `Option<${sorobanToRust(type.inner as any)}>`;
    case 'result': return `Result<${sorobanToRust(type.ok as any)}, Error>`;
    case 'struct': case 'enum': case 'union': case 'udt': return type.name || 'Val';
    case 'tuple': return 'Val /* tuple */';
    default: return 'Val';
  }
}

function snakeCase(name: string): string {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

function capitalize(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function generateMethods(abi: ContractABI): string {
  return abi.functions.map(fn => {
    const params = fn.params.map(p => {
      const ty = sorobanToRust(p.type);
      const doc = p.docs ? ` /// ${p.docs}` : '';
      return `        ${snakeCase(p.name)}: ${ty},${doc}`;
    }).join('\n');

    const paramNamesList = fn.params.map(p => snakeCase(p.name));
    const paramNames = paramNamesList.join(', ');
    const returnTy = fn.returns.kind === 'void' ? '()' : sorobanToRust(fn.returns);
    const callArgs = paramNamesList.length > 0 ? `vec![${paramNamesList.map(n => `${n}.into()`).join(', ')}]` : 'vec![]';

    return `    /// ${fn.docs || `${fn.name} — contract function.`}
    pub async fn ${snakeCase(fn.name)}(&self, env: &Env${fn.params.length > 0 ? `,\n${params}` : ''}) -> Result<${returnTy}, Error> {
        Ok(self.client.invoke_contract::<${returnTy}>(
            &env,
            &self.contract_id,
            "${fn.name}",
            ${callArgs},
        )?)
    }`;
  }).join('\n\n');
}

export function generateRustClient(opts: RustClientOptions): SDKOutput {
  const { abi, packageName, version, contractId } = opts;

  const methods = generateMethods(abi);

  const libContent = `use soroban_sdk::{Env, Address, BytesN, Symbol, Val, Vec, Map, Error};
use soroban_sdk::contractclient::Client;

/// Client for the ${abi.name} Soroban smart contract.
///
/// Auto-generated by SoroDoc from contract ABI.
${contractId ? `/// Contract ID: ${contractId}` : ''}
pub struct ${abi.name}Client {
    client: Client,
    contract_id: BytesN<32>,
}

impl ${abi.name}Client {
    /// Create a new contract client.
    pub fn new(contract_id: BytesN<32>) -> Self {
        Self {
            client: Client::new(),
            contract_id,
        }
    }

${methods}
}
`;

  const files = new Map<string, string>();
  files.set('src/lib.rs', libContent);

  files.set('Cargo.toml', `[package]
name = "${abi.name.toLowerCase()}-client"
version = "${version || '0.1.0'}"
edition = "2021"
description = "${abi.name} Soroban contract Rust client"

[dependencies]
soroban-sdk = "21.0.0"
tokio = { version = "1", features = ["full"] }

[lib]
crate-type = ["lib", "cdylib"]
`);

  const readme = `# ${abi.name} Rust Client

${abi.name} — Soroban Smart Contract Rust Client

**Package:** \`${packageName || `${abi.name.toLowerCase()}-client`}\`
${contractId ? `**Contract ID:** \`${contractId}\`` : ''}

## Usage

\`\`\`rust
use ${abi.name.toLowerCase()}_client::${abi.name}Client;

let client = ${abi.name}Client::new(contract_id);
\`\`\`

---

*Generated by SoroDoc*
`;

  return { files, packageJson: { name: packageName, version: version || '0.1.0' }, readme };
}
