import fs from 'node:fs';
import path from 'node:path';
import { DocOutput, GeneratedOutput } from '../types.js';
import { MarkdownRenderer } from './MarkdownRenderer.js';

export interface DocusaurusRendererOptions {
  outputDir: string;
  contractId?: string;
  network?: string;
  projectName?: string;
  tagline?: string;
}

const DOCUSAURUS_CONFIG = (name: string, tagline: string) => `module.exports = {
  title: '${name}',
  tagline: '${tagline}',
  url: 'https://docs.sorodoc.dev',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'sorodoc',
  projectName: '${name.toLowerCase().replace(/\s+/g, '-')}',
  themeConfig: {
    navbar: {
      title: '${name}',
      items: [
        { to: '/docs/overview', label: 'Docs', position: 'left' },
        { to: '/docs/sdk/quickstart', label: 'SDK', position: 'left' },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: 'Generated by SoroDoc',
    },
  },
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: undefined,
        },
        theme: { customCss: require.resolve('./src/css/custom.css') },
      },
    ],
  ],
};
`;

const SIDEBARS = `module.exports = {
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Functions',
      items: [FUNCTIONS_PLACEHOLDER],
    },
    {
      type: 'category',
      label: 'Events',
      items: [EVENTS_PLACEHOLDER],
    },
    {
      type: 'category',
      label: 'Errors',
      items: ['errors/error-reference'],
    },
    {
      type: 'category',
      label: 'SDK',
      items: ['sdk/quickstart'],
    },
  ],
};
`;

export class DocusaurusRenderer {
  private options: DocusaurusRendererOptions;

  constructor(options: DocusaurusRendererOptions) {
    this.options = options;
  }

  render(output: DocOutput): GeneratedOutput {
    const baseDir = path.resolve(this.options.outputDir, 'docusaurus');

    const dirs = [
      'docs/functions',
      'docs/events',
      'docs/errors',
      'docs/sdk',
      'src/css',
      'static/img',
    ];
    for (const dir of dirs) {
      fs.mkdirSync(path.join(baseDir, dir), { recursive: true });
    }

    // Generate docusaurus config
    fs.writeFileSync(
      path.join(baseDir, 'docusaurus.config.js'),
      DOCUSAURUS_CONFIG(this.options.projectName || output.contractName, this.options.tagline || 'Soroban Smart Contract'),
      'utf8',
    );

    // Generate sidebars
    const fnItems = output.functions.map(f => `'functions/${f.name}'`).join(', ');
    const eventItems = output.events.map(e => `'events/${e.name}'`).join(', ');
    fs.writeFileSync(
      path.join(baseDir, 'sidebars.js'),
      SIDEBARS.replace('FUNCTIONS_PLACEHOLDER', fnItems || "'placeholder'").replace('EVENTS_PLACEHOLDER', eventItems || "'placeholder'"),
      'utf8',
    );

    // Generate CSS
    fs.writeFileSync(
      path.join(baseDir, 'src/css/custom.css'),
      `:root { --ifm-color-primary: #4f46e5; --ifm-color-primary-dark: #4338ca; }\n`,
      'utf8',
    );

    // Generate markdown content using MarkdownRenderer into docs/
    const mdRenderer = new MarkdownRenderer({
      outputDir: baseDir,
      contractId: this.options.contractId,
      network: this.options.network,
    });
    mdRenderer.render(output);

    // Rename markdown/index.md to docs/overview.md for docusaurus
    const oldOverview = path.join(baseDir, 'markdown/index.md');
    const newOverview = path.join(baseDir, 'docs/overview.md');
    if (fs.existsSync(oldOverview)) {
      fs.renameSync(oldOverview, newOverview);
    }

    // Move markdown content into docs/
    const markdownDir = path.join(baseDir, 'markdown');
    if (fs.existsSync(markdownDir)) {
      for (const entry of fs.readdirSync(markdownDir, { withFileTypes: true })) {
        const src = path.join(markdownDir, entry.name);
        const dest = path.join(baseDir, 'docs', entry.name);
        if (entry.isDirectory()) {
          fs.cpSync(src, dest, { recursive: true });
        } else if (entry.isFile()) {
          fs.renameSync(src, dest);
        }
      }
      fs.rmSync(markdownDir, { recursive: true, force: true });
    }

    let fileCount = 0;
    const countFiles = (dir: string) => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.isFile()) fileCount++;
        else if (entry.isDirectory()) countFiles(path.join(dir, entry.name));
      }
    };
    countFiles(baseDir);

    return {
      docs: output,
      markdown: `Generated Docusaurus site (${fileCount} files) in ${baseDir}`,
    };
  }
}
