import fs from 'node:fs';
import path from 'node:path';
import { DocOutput, DocFunction, DocEvent, DocError, GeneratedOutput } from '../types.js';

export interface MarkdownRendererOptions {
  outputDir: string;
  contractId?: string;
  network?: string;
}

export class MarkdownRenderer {
  private options: MarkdownRendererOptions;

  constructor(options: MarkdownRendererOptions) {
    this.options = options;
  }

  render(output: DocOutput): GeneratedOutput {
    const baseDir = path.resolve(this.options.outputDir, 'markdown');
    fs.mkdirSync(path.join(baseDir, 'functions'), { recursive: true });
    fs.mkdirSync(path.join(baseDir, 'events'), { recursive: true });
    fs.mkdirSync(path.join(baseDir, 'errors'), { recursive: true });
    fs.mkdirSync(path.join(baseDir, 'sdk'), { recursive: true });

    const files: Map<string, string> = new Map();

    files.set('index.md', this.renderOverview(output));
    files.set('sdk/quickstart.md', this.renderQuickstart(output));

    for (const fn of output.functions) {
      files.set(`functions/${fn.name}.md`, this.renderFunction(fn));
    }

    for (const evt of output.events) {
      files.set(`events/${evt.name}.md`, this.renderEvent(evt));
    }

    files.set('errors/error-reference.md', this.renderErrorReference(output.errors));

    for (const [filePath, content] of files) {
      const fullPath = path.join(baseDir, filePath);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf8');
    }

    const fileCount = files.size;

    return {
      docs: output,
      markdown: `Generated ${fileCount} markdown files in ${baseDir}`,
    };
  }

  private renderOverview(output: DocOutput): string {
    const fnList = output.functions.map(f =>
      `- [${f.name}](functions/${f.name}.md) — ${f.description.split('\n')[0]}`
    ).join('\n');

    const eventList = output.events.map(e =>
      `- [${e.name}](events/${e.name}.md) — ${e.description.split('\n')[0]}`
    ).join('\n');

    const errorList = output.errors.map(e =>
      `- \`${e.name}\` (code ${e.code}) — ${e.description.split('\n')[0]}`
    ).join('\n');

    return `---
title: "${output.contractName}"
description: "Soroban smart contract — ${output.contractName}"
---

# ${output.contractName}

${output.overview}

## Functions

${fnList || '*No functions defined*'}

## Events

${eventList || '*No events defined*'}

## Errors

${errorList || '*No errors defined*'}

---

*Generated by SoroDoc*
`;
  }

  private renderFunction(fn: DocFunction): string {
    const paramsTable = fn.params.map(p => {
      const typeStr = JSON.stringify(p.type);
      const examples = p.examples?.length ? `<br>**Examples:** ${p.examples.join(', ')}` : '';
      return `| \`${p.name}\` | \`${typeStr}\` | ${p.description}${examples} |`;
    }).join('\n');

    const errorTable = fn.errors?.map(e =>
      `| [${e.name}](../errors/error-reference.md#${e.name.toLowerCase()}) | ${e.code} | ${e.description} |`
    ).join('\n');

    const exampleSection = fn.examples?.length
      ? `\n## Examples\n\n${fn.examples.map(ex =>
          `### ${ex.language}\n\n\`\`\`${ex.language}\n${ex.code}\n\`\`\``
        ).join('\n')}\n`
      : '';

    return `---
title: "${fn.name}"
description: "${fn.description.split('\n')[0]}"
---

# ${fn.name}

${fn.description}

## Parameters

${paramsTable ? `| Parameter | Type | Description |\n|-----------|------|-------------|\n${paramsTable}` : '*No parameters*'}

## Returns

\`${JSON.stringify(fn.returns.type)}\` — ${fn.returns.description}

${errorTable ? `## Errors\n\n| Error | Code | Description |\n|-------|------|-------------|\n${errorTable}\n` : ''}
${exampleSection}
---

*Function documentation for \`${fn.name}\`*
`;
  }

  private renderEvent(evt: DocEvent): string {
    const topicTable = evt.topics.map(t =>
      `| \`${t.name}\` | \`${JSON.stringify(t.type)}\` | ${t.docs || ''} |`
    ).join('\n');

    const dataTable = evt.data.map(d =>
      `| \`${d.name}\` | \`${JSON.stringify(d.type)}\` | ${d.docs || ''} |`
    ).join('\n');

    const exampleSection = evt.example
      ? `\n## Example\n\n\`\`\`\n${evt.example}\n\`\`\`\n`
      : '';

    return `---
title: "${evt.name} (event)"
description: "${evt.description.split('\n')[0]}"
---

# ${evt.name}

${evt.description}

## Topics

${topicTable ? `| Topic | Type | Description |\n|-------|------|-------------|\n${topicTable}` : '*No topics*'}

## Data

${dataTable ? `| Field | Type | Description |\n|-------|------|-------------|\n${dataTable}` : '*No data fields*'}
${exampleSection}
---

*Event documentation for \`${evt.name}\`*
`;
  }

  private renderErrorReference(errors: DocError[]): string {
    const rows = errors.map(e =>
      `## ${e.name} (code ${e.code})\n\n${e.description}\n\n**Common causes:**\n${e.commonCauses.map(c => `- ${c}`).join('\n') || '*None documented*'}\n\n**Remediation:**\n${e.remediation || '*No remediation documented*'}\n`
    ).join('\n---\n\n');

    return `---
title: "Error Reference"
description: "Complete error catalogue for ${errors.length > 0 ? 'the contract' : 'contract errors'}"
---

# Error Reference

${errors.length === 0 ? '*No errors defined for this contract*' : rows}

---

*Error documentation for the contract*
`;
  }

  private renderQuickstart(output: DocOutput): string {
    const fnNames = output.functions.map(f => `\`${f.name}\``).join(', ');

    return `---
title: "SDK Quickstart"
description: "Getting started with the ${output.contractName} SDK"
---

# ${output.contractName} SDK Quickstart

## Installation

\`\`\`bash
npm install @sorodoc/${output.contractName.toLowerCase()}-sdk
\`\`\`

## Usage

\`\`\`typescript
import { ${output.contractName}Contract } from '@sorodoc/${output.contractName.toLowerCase()}-sdk';

const contract = new ${output.contractName}Contract({
  contractId: '${this.options.contractId || 'YOUR_CONTRACT_ID'}',
  networkPassphrase: '${this.options.network === 'mainnet' ? 'Public Global Stellar Network ; September 2015' : 'Test SDF Network ; September 2015'}',
  rpcUrl: '${this.options.network === 'mainnet' ? 'https://soroban-rpc.mainnet.stellar.org' : 'https://soroban-rpc.testnet.stellar.org'}',
});
\`\`\`

## Available Functions

${fnNames || '*No functions available*'}

## Next Steps

- Explore the [function reference](../index.md) for detailed documentation
- Check the [error reference](../errors/error-reference.md) for troubleshooting

---

*SDK quickstart for \`${output.contractName}\`*
`;
  }
}
